### ISSUE TITLE
[DO NOT USE THIS] The compiled version contains a Discord stealer

### ISSUE THREAD

**Issue by ghost** [NebulaOnTop/HWID-Spoofer-for-Fortnite-and-Valorant#2]
### **Quite disgusting that this has become the default for this type of software on GitHub...**

Be careful when looking for various HWID spoofers on this site. Nowadays, almost every compiled version contains a Bitcoin miner or a Discord stealer. My ignorance for not looking through the source code beforehand, although, I doubt it was even included in the *public* source code.

*The compiled version definitely functions as a Trojan.*

**Comment by ghost** [comment]
_See: https://prnt.sc/1y2dli9_ **[PROOF]**

**Comment by Azzerzz** [comment]
> _See: https://prnt.sc/1y2dli9_ **[PROOF]**

you are fucking stupid.
thats not proof you fucking ape

**Comment by ghost** [comment]
> > _See: https://prnt.sc/1y2dli9_ **[PROOF]**
> 
> you are fucking stupid. thats not proof you fucking ape

Feel free to open the compiled version yourself, you incel mongoloid.

**Comment by Customscript** [comment]
Token logger... LOL what a RAT
